Traceback (most recent call last):
  File "main.py", line 227, in <module>
    val_metric_results = algorithm.evaluate(loader, cache = validation_cache[index])
  File "/data/healthy-ml/scratch/odahleh/mimic-mil/algorithms.py", line 459, in evaluate
    result = self._evaluate_robust(self.network, loader, self.hparams['metrics'], cache)
  File "/data/healthy-ml/scratch/odahleh/mimic-mil/algorithms.py", line 406, in _evaluate_robust
    p, _ = self.predict(x, y, return_context=True, past_key_values=initial_past)
  File "/data/healthy-ml/scratch/odahleh/mimic-mil/algorithms.py", line 348, in predict
    outputs = self.classifier((x, y, None, past_key_values))
  File "/data/healthy-ml/scratch/odahleh/anaconda3/envs/icrm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/healthy-ml/scratch/odahleh/mimic-mil/networks.py", line 196, in forward
    outputs = self._backbone(inputs_embeds=embeds, past_key_values=past_key_values)
  File "/data/healthy-ml/scratch/odahleh/anaconda3/envs/icrm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/healthy-ml/scratch/odahleh/anaconda3/envs/icrm/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1132, in forward
    outputs = block(
  File "/data/healthy-ml/scratch/odahleh/anaconda3/envs/icrm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/healthy-ml/scratch/odahleh/anaconda3/envs/icrm/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 615, in forward
    attn_outputs = self.attn(
  File "/data/healthy-ml/scratch/odahleh/anaconda3/envs/icrm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/healthy-ml/scratch/odahleh/anaconda3/envs/icrm/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 332, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/data/healthy-ml/scratch/odahleh/anaconda3/envs/icrm/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 203, in _attn
    attn_weights = torch.where(causal_mask, attn_weights.to(attn_weights.dtype), mask_value)
RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 3
