Traceback (most recent call last):
  File "main.py", line 219, in <module>
    step_metrics = algorithm.update(minibatches_device)
  File "/data/healthy-ml/scratch/odahleh/mimic-mil/algorithms.py", line 88, in update
    out = self.predict(x, y)
  File "/data/healthy-ml/scratch/odahleh/mimic-mil/algorithms.py", line 299, in predict
    outputs = self.classifier((x, y, None, past_key_values))
  File "/data/healthy-ml/scratch/odahleh/anaconda3/envs/icrm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/healthy-ml/scratch/odahleh/mimic-mil/networks.py", line 189, in forward
    inds = torch.arange(ys.shape[1])
IndexError: tuple index out of range
